# Fintech Portfolio Tracker

This project fetches stock market data using Python and prepares data for portfolio analysis and dashboard visualization.

!pip install yfinance

In [2]:
import yfinance as yf #yfinance is a finance data specific python library that will fetch data from yahoo finance
import pandas as pd

In [3]:
ticker = "AAPL"

stock_data = yf.download(ticker, period="5d")

stock_data.head()

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2026-05-08  293.050018  294.488695  289.733067  289.743067  52692800
2026-05-11  292.679993  293.880005  290.230011  291.980011  42247300
2026-05-12  294.799988  295.269989  292.559998  292.559998  45748100
2026-05-13  298.869995  300.920013  293.500000  293.500000  52684300
2026-05-14  298.209991  300.450012  295.380005  299.820007  35263400

In [10]:
tickers = ["AAPL", "MSFT", "JPM", "PFE", "XOM"]

portfolio_data = yf.download(tickers, period="1mo")

portfolio_data.head()

[*********************100%***********************]  5 of 5 completed

Price            Close                                                 \
Ticker            AAPL         JPM        MSFT        PFE         XOM
Date
2026-04-15  266.184753  305.929993  411.220001  26.748470  149.009995
2026-04-16  263.157532  309.950012  420.260010  26.777983  151.979996
2026-04-17  269.981262  310.290009  422.790009  27.112461  146.440002
2026-04-20  272.798645  316.989990  418.070007  27.073112  147.679993
2026-04-21  265.925018  313.000000  424.160004  26.866520  148.360001

Price             High                                                 ...  \
Ticker            AAPL         JPM        MSFT        PFE         XOM  ...
Date                                                                   ...
2026-04-15  266.314639  314.239990  414.369995  26.915710  150.229996  ...
2026-04-16  266.914080  309.950012  420.820007  27.033761  152.779999  ...
2026-04-17  272.049334  314.899994  431.579987  27.220675  146.800003  ...
2026-04-20  274.027524  317.130005  423.329987  27.397754  149.369995  ...
2026-04-21  272.548890  320.239990  427.179993  27.171487  148.809998  ...

Price             Open                                                 \
Ticker            AAPL         JPM        MSFT        PFE         XOM
Date
2026-04-15  257.922377  313.950012  398.000000  26.738632  148.600006
2026-04-16  266.554396  305.350006  419.859985  26.768145  149.529999
2026-04-17  266.714253  312.470001  424.820007  26.886196  144.860001
2026-04-20  270.081148  310.850006  421.149994  27.141975  147.380005
2026-04-21  271.250099  317.489990  420.239990  27.073111  147.369995

Price         Volume
Ticker          AAPL       JPM      MSFT       PFE       XOM
Date
2026-04-15  49913500   9885800  45063400  29648900  15626500
2026-04-16  43323100   8208600  41642400  21905300  15191000
2026-04-17  61436200  11082400  48568200  30080400  28947400
2026-04-20  36590200  10772000  27582200  25023000  16354400
2026-04-21  50209800   7084300  32048500  29833000  17515900

[5 rows x 25 columns]

In [9]:
stock_dictionary = {"Finance":["BCS","HDFCBANK.NS","MS","DB","ICICIBANK.NS"],
                   "Technology":["AAPL","AMZN","TCS.NS","WIPRO.NS","GOOG"],
                   "Health": ["PFE","JNJ","MRK","SUNPHARMA.NS","DRREDDY.NS"],
                   "Automobile":["TSLA","F","TM","TATAMOTORS.NS","BAJAJ-AUTO.NS"]}
tickers = []
for stocks in stock_dictionary:
    tickers.extend(stocks)

portfolio_data = yf.download(tickers, period="5d")

portfolio_data.head(5)

[******                13%                       ]  2 of 15 completed$N: possibly delisted; no price data found  (period=5d)
[**********************60%****                   ]  9 of 15 completed$I: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[**********************73%**********             ]  11 of 15 completed$Y: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")
[*********************100%***********************]  15 of 15 completed

3 Failed downloads:
['N']: possibly delisted; no price data found  (period=5d)
['I', 'Y']: possibly delisted; no price data found  (period=5d) (Yahoo error = "No data found, symbol may be delisted")

Price      Adj Close               Close                                    \
Ticker             I   N   Y           A          B           C          E
Date
2026-05-08       NaN NaN NaN  115.620003  43.130001  125.550003  53.430000
2026-05-11       NaN NaN NaN  111.459999  47.000000  125.849998  55.459999
2026-05-12       NaN NaN NaN  112.900002  45.849998  126.440002  55.830002
2026-05-13       NaN NaN NaN  112.739998  44.869999  124.099998  55.520000
2026-05-14       NaN NaN NaN  113.260002  43.160000  124.820000  55.330002

Price                                         ...   Volume               \
Ticker              F          G           H  ...        G        H   I
Date                                          ...
2026-05-08  12.166638  32.560001  167.600006  ...  5439100  1064800 NaN
2026-05-11  11.900001  31.299999  165.149994  ...  4159400   514800 NaN
2026-05-12  11.990000  31.250000  166.470001  ...  3656400   596100 NaN
2026-05-13  13.570000  29.440001  167.259995  ...  3783900   597100 NaN
2026-05-14  14.480000  28.940001  169.979996  ...  4748900   767900 NaN

Price
Ticker            L        M   N        O         T         U   Y
Date
2026-05-08  1005400  3806700 NaN  7270800  36012900  17315100 NaN
2026-05-11   862400  6547200 NaN  5683200  37447600  14314400 NaN
2026-05-12   811800  5443600 NaN  5549500  33454600   8529200 NaN
2026-05-13   721400  5229300 NaN  6456300  34609700   6589200 NaN
2026-05-14  1019700  5598300 NaN  6049100  32649500   7985100 NaN

[5 rows x 78 columns]