# Fintech Portfolio Tracker

This project fetches stock market data using Python and prepares data for portfolio analysis and dashboard visualization.

In [14]:
import yfinance as yf 
import pandas as pd

In [9]:
stock_dictionary = {
    "Finance": ["JPM", "MS", "GS", "BAC", "C"],
    "Technology": ["AAPL", "MSFT", "AMZN", "GOOG", "NVDA"],
    "Healthcare": ["PFE", "JNJ", "MRK", "UNH", "ABBV"],
    "Automobile": ["TSLA", "F", "GM", "TM", "RIVN"]
}
tickers = []

for stocks in stock_dictionary.values():
    tickers.extend(stocks)

portfolio_data = yf.download(tickers, period="5d")

[*********************100%***********************]  20 of 20 completed

Price            Close                                                 \
Ticker            AAPL        ABBV        AMZN        BAC           C
Date
2026-05-11  292.679993  202.779999  268.989990  50.549999  125.849998
2026-05-12  294.799988  207.860001  265.820007  50.779999  126.440002
2026-05-13  298.869995  208.500000  270.130005  49.840000  124.099998
2026-05-14  298.209991  210.770004  267.220001  49.849998  124.820000
2026-05-15  300.230011  210.389999  264.140015  49.770000  123.419998

Price                                                                 ...  \
Ticker              F         GM        GOOG          GS         JNJ  ...
Date                                                                  ...
2026-05-11  11.900001  75.290001  386.769989  944.859985  221.429993  ...
2026-05-12  11.990000  76.440002  383.820007  945.900024  224.259995  ...
2026-05-13  13.570000  75.809998  399.040009  955.419983  230.419998  ...
2026-05-14  14.480000  77.750000  397.170013  968.960022  230.800003  ...
2026-05-15  13.400000  74.860001  393.320007  948.469971  226.710007  ...

Price        Volume                                                    \
Ticker          JPM       MRK       MS      MSFT       NVDA       PFE
Date
2026-05-11  9512000   7750600  5272500  35657900  160685800  43558000
2026-05-12  9498200   9117400  5333300  38594200  159176600  26819500
2026-05-13  7709500   8110500  4463700  29667100  150405400  39420000
2026-05-14  7364300   5284200  4785000  27077500  180782900  24102700
2026-05-15  8659900  10022000  5925200  50310800  179993300  37069400

Price
Ticker          RIVN      TM      TSLA      UNH
Date
2026-05-11  26215700  609500  78376100  6949600
2026-05-12  22253000  651100  60569300  9236300
2026-05-13  29255400  590600  68283200  8454100
2026-05-14  21303700  399800  46070400  5342500
2026-05-15  42095800  561100  52271800  9682200

[5 rows x 100 columns]

In [13]:
clean_portfolio_table.head(5)

             Close        High         Low        Open    Volume
Ticker
AAPL    300.230011  303.200012  296.519989  297.899994  54721100
ABBV    210.389999  214.919998  209.020004  213.100006   5355900
AMZN    264.140015  264.359985  260.890015  262.500000  40672200
BAC      49.770000   49.990002   49.299999   49.619999  45998300
C       123.419998  124.500000  122.730003  124.480003   7759200

In [3]:
ticker = "AAPL"

stock_data = yf.download(ticker, period="5d")

stock_data.head()

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2026-05-11  292.679993  293.880005  290.230011  291.980011  42247300
2026-05-12  294.799988  295.269989  292.559998  292.559998  45748100
2026-05-13  298.869995  300.920013  293.500000  293.500000  52684300
2026-05-14  298.209991  300.450012  295.380005  299.820007  35324900
2026-05-15  300.230011  303.200012  296.519989  297.899994  54721100

!pip install yfinance  #yfinance is a finance data specific python library that will fetch data from yahoo finance

In [10]:
latest_close = portfolio_data["Close"].iloc[-1]
latest_high = portfolio_data["High"].iloc[-1]
latest_low = portfolio_data["Low"].iloc[-1]
latest_open = portfolio_data["Open"].iloc[-1]
latest_volume = portfolio_data["Volume"].iloc[-1]

In [12]:
clean_portfolio_table = pd.DataFrame({
    "Close": latest_close,
    "High": latest_high,
    "Low": latest_low,
    "Open": latest_open,
    "Volume": latest_volume
})

             Close        High         Low        Open    Volume
Ticker
AAPL    300.230011  303.200012  296.519989  297.899994  54721100
ABBV    210.389999  214.919998  209.020004  213.100006   5355900
AMZN    264.140015  264.359985  260.890015  262.500000  40672200
BAC      49.770000   49.990002   49.299999   49.619999  45998300
C       123.419998  124.500000  122.730003  124.480003   7759200